name: Telegram Auto Poster

on:
  schedule:
    - cron: '0 * * * *'  # каждый час на нулевой минуте (UTC)
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    concurrency:
      group: telegram-auto-poster
      cancel-in-progress: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install fonts (DejaVu)
        run: sudo apt-get update && sudo apt-get install -y fonts-dejavu-core

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run bot
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          CHANNEL_HANDLE: ${{ secrets.CHANNEL_HANDLE }}
        run: python bot.py
